services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
       - DATABASE_URL=${DATABASE_URL}
       - SECRET=${SECRET}
    depends_on:
      - db
    command: sh -c "alembic upgrade head && cd /app && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 "
    

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: